"""Rendering of OpenVPN server and client configuration.

The panel owns the whole configuration: nodes and clients never hold state the
panel cannot rebuild from the database.
"""

import ipaddress
import logging
import time
from pathlib import Path

from app.core.config import settings
from app.core.crypto import decrypt_secret
from app.models.node import Client, Node
from app.models.pki import CertificateAuthority
from app.services import pki

logger = logging.getLogger("aeolus.openvpn")


class OpenVpnError(Exception):
    """Configuration could not be produced. Safe to show to an operator."""


def tunnel_subnet(proto: str) -> str:
    return settings.vpn_subnet if proto == "udp" else settings.vpn_tcp_subnet


def static_address(proto: str, host: int) -> str:
    """The fixed tunnel address of a pinned client on one listener.

    A node runs two listeners on two subnets, so a pinned client has an address
    on each; only the host part is stored.
    """
    network = ipaddress.ip_network(f"{tunnel_subnet(proto)}/{settings.vpn_netmask}")
    return str(network.network_address + host)


def render_server_config(node: Node, *, proto: str | None = None, port: int | None = None) -> str:
    """Server config for one listener of a node. Certificates live in siblings."""
    proto = proto or node.openvpn_proto
    port = port or node.openvpn_port
    # TCP needs its own status file and management port, or the two instances
    # would overwrite each other.
    suffix = "" if proto == "udp" else "-tcp"
    pool_start = static_address(proto, settings.vpn_pool_host_min)
    pool_end = static_address(proto, settings.vpn_pool_host_max)
    return f"""# Generated by Aeolus. Changes are overwritten on restart.
port {port}
proto {"tcp-server" if proto == "tcp" else "udp"}
dev tun
topology subnet

# `nopool` because the pool below is narrower than the subnet: everything under
# it is reserved for clients the panel pins to a fixed address, so a dynamic
# lease can never take an address that belongs to someone. OpenVPN refuses an
# explicit ifconfig-pool unless `server` is told not to define one itself.
server {tunnel_subnet(proto)} {settings.vpn_netmask} nopool
ifconfig-pool {pool_start} {pool_end} {settings.vpn_netmask}
# No global redirect-gateway: whether a client's default route comes here is a
# per-client decision, pushed from its ccd file. Sending it to everyone would
# blackhole the clients that are only allowed to reach a couple of subnets.
push "dhcp-option DNS {settings.vpn_dns}"

ca ca.crt
cert server.crt
key server.key
# EC certificates use ECDH, so no Diffie-Hellman parameter file is needed.
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
# OpenVPN re-reads the CRL on every handshake, so rewriting this file is enough
# to start refusing a revoked client.
crl-verify crl.pem
# One directory per listener: the fixed addresses inside differ between the UDP
# and the TCP subnet.
client-config-dir ccd{suffix}
# The same CA also signs node certificates, and a node has no business dialling
# in as a VPN client. Only names the panel wrote a file for may connect.
ccd-exclusive

data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client

# A 1500-byte tunnel MTU makes the encapsulated packet exceed the path MTU on
# most mobile networks, which drop it. Small packets then work while anything
# large — TLS, QUIC — silently stalls. Leave headroom for the UDP, tls-crypt and
# AES-GCM overhead, and clamp TCP MSS to match.
tun-mtu {settings.vpn_tun_mtu}
mssfix {settings.vpn_mssfix}

# Follow a session that changes source port. Home routers routinely remap the
# port of a long-lived UDP flow, and without this the server keeps answering the
# port it first saw: the peer hears nothing, times out and reconnects, forever.
# Safe because a packet only moves the session after it authenticates, which
# tls-crypt and the HMAC already require.
float

keepalive 10 120
persist-key
persist-tun
user nobody
group nogroup

status /run/openvpn/status{suffix}.log 5
management 127.0.0.1 {7505 if proto == "udp" else 7506}
verb 3
"""


def transit_address(host: int) -> str:
    network = ipaddress.ip_network(
        f"{settings.vpn_transit_subnet}/{settings.vpn_netmask}"
    )
    return str(network.network_address + host)


def render_transit_server_config(nodes: list[Node]) -> str:
    """The listener every node dials into, run on the hub.

    Nodes are OpenVPN clients here, which is what keeps a node free of inbound
    ports. `ccd-exclusive` means only a name the panel wrote a file for may
    connect: our CA also signs VPN clients, and none of them belong on this
    listener.
    """
    routes = []
    for node in nodes:
        for subnet in node.subnets or []:
            net = ipaddress.ip_network(subnet)
            # The kernel route sends the LAN to the tun device; the matching
            # iroute in the node's ccd file picks which tunnel inside it.
            routes.append(f"route {net.network_address} {net.netmask}")

    route_block = "\n".join(routes) or "# no node subnets announced yet"

    transit_proto = settings.vpn_transit_proto
    return f"""# Generated by Aeolus. Changes are overwritten on restart.
port {settings.vpn_transit_port}
proto {"tcp-server" if transit_proto == "tcp" else "udp"}
dev tun
topology subnet

server {settings.vpn_transit_subnet} {settings.vpn_netmask}
# Nodes need a way back to the client pools: a client's packet reaches a node
# with its own address as the source, and the reply has to find the tunnel it
# came from rather than the node's default route.
push "route {settings.vpn_subnet} {settings.vpn_netmask}"
push "route {settings.vpn_tcp_subnet} {settings.vpn_netmask}"
client-config-dir ccd-transit
# Only nodes the panel knows about, by name.
ccd-exclusive

{route_block}

ca ca.crt
cert server.crt
key server.key
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
crl-verify crl.pem

data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client

tun-mtu {settings.vpn_tun_mtu}
mssfix {settings.vpn_mssfix}

# Follow a session that changes source port. Home routers routinely remap the
# port of a long-lived UDP flow, and without this the server keeps answering the
# port it first saw: the peer hears nothing, times out and reconnects, forever.
# Safe because a packet only moves the session after it authenticates, which
# tls-crypt and the HMAC already require.
float

keepalive 10 60
persist-key
persist-tun

status /run/openvpn/status-transit.log 5
management 127.0.0.1 7507
verb 3
"""


def render_transit_client_config(node: Node, hub_address: str) -> str:
    """What a node runs to reach the hub. The node is a client here."""
    transit_proto = settings.vpn_transit_proto
    return f"""# Aeolus transit · node {node.name}
client
dev tun
proto {"tcp-client" if transit_proto == "tcp" else "udp"}
remote {hub_address} {settings.vpn_transit_port} {transit_proto}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server

ca ca.crt
cert transit.crt
key transit.key
tls-crypt tls-crypt.key

data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2

tun-mtu {settings.vpn_tun_mtu}
mssfix {settings.vpn_mssfix}
keepalive 10 60

status /run/openvpn/status-transit.log 5
verb 3
"""


def render_transit_ccd(node: Node) -> str:
    """The hub's ccd entry for one node: its address and the LANs behind it."""
    if node.transit_host is None:
        return f"# {node.name}: no transit address assigned\ndisable\n"

    lines = [
        f"# {node.name} — сгенерировано Aeolus",
        f"ifconfig-push {transit_address(node.transit_host)} {settings.vpn_netmask}",
    ]
    for subnet in node.subnets or []:
        net = ipaddress.ip_network(subnet)
        lines.append(f"iroute {net.network_address} {net.netmask}")
    return "\n".join(lines) + "\n"


def render_client_config(client: Client, node: Node, ca: CertificateAuthority) -> str:
    """A single self-contained .ovpn file with everything inlined."""
    if client.cert_pem is None or client.key_pem_encrypted is None:
        raise OpenVpnError(
            f"{client.common_name} has no certificate yet; issue one in the pki section"
        )
    if client.revoked_at is not None:
        raise OpenVpnError(f"{client.common_name} is revoked")

    key_pem = decrypt_secret(client.key_pem_encrypted)
    tls_crypt = decrypt_secret(ca.tls_crypt_key_encrypted)

    # Plain repeated remote lines, not <connection> blocks: options that follow a
    # connection block are silently ignored by OpenVPN 2.x, which would drop
    # tls-crypt and leave the profile unusable. The client tries these in order,
    # so UDP comes first — it is faster, and TCP-in-TCP degrades badly on loss.
    remotes = f"remote {node.address} {node.openvpn_port} {node.openvpn_proto}"
    if node.tcp_port:
        remotes += f"\nremote {node.address} {node.tcp_port} tcp"

    return f"""# Aeolus · {client.common_name} via {node.name}
client
dev tun
{remotes}
# Move on to the next remote instead of retrying a transport the network mangles.
connect-retry-max 2
server-poll-timeout 12
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
verb 3

<ca>
{ca.cert_pem.strip()}
</ca>
<cert>
{client.cert_pem.strip()}
</cert>
<key>
{key_pem.strip()}
</key>
<tls-crypt>
{tls_crypt.strip()}
</tls-crypt>
"""


async def sync_local_crl(session) -> bool:
    """Refresh the CRL the local OpenVPN reads.

    Revocation is only real once the node has the new list, so this runs on
    every revoke rather than waiting for the next restart. Remote nodes will get
    the same file from the anemoi agent.
    """
    target = Path(settings.openvpn_config_dir)
    if not target.exists():
        return False

    crl_pem = await pki.build_crl(session)
    (target / "crl.pem").write_text(crl_pem)
    logger.warning("Refreshed CRL at %s", target / "crl.pem")
    return True


async def sync_routing_plan(session) -> bool:
    """Write the routing plan the local supervisor applies.

    Runs on every change that can affect who may reach what — a grant, an exit,
    a client's status — because a rule that has not reached the kernel is not a
    rule at all.
    """
    from app.services import routing

    target = Path(settings.openvpn_config_dir)
    if not target.exists():
        return False

    plan = await routing.build_plan(session)
    path = target / "routing.json"
    rendered = routing.render(plan)
    if path.exists() and path.read_text() == rendered:
        return False

    path.write_text(rendered)
    path.chmod(0o644)
    logger.warning("Wrote routing plan %s to %s", plan["revision"], path)
    return True


def write_server_bundle(node: Node, ca: CertificateAuthority, crl_pem: str) -> Path:
    """Write everything the local OpenVPN process needs into the shared volume.

    Used for the panel's own node; remote nodes will get the same bundle pushed
    by the anemoi agent instead.
    """
    if node.server_cert_pem is None or node.server_key_pem_encrypted is None:
        raise OpenVpnError(f"node {node.name} has no server certificate")

    target = Path(settings.openvpn_config_dir)
    target.mkdir(parents=True, exist_ok=True)
    # Both listeners need their directory to exist before OpenVPN starts, even
    # when the agent has not filled them in yet.
    (target / "ccd").mkdir(exist_ok=True)
    (target / "ccd-tcp").mkdir(exist_ok=True)

    files = {
        "ca.crt": ca.cert_pem,
        "server.crt": node.server_cert_pem,
        "server.key": decrypt_secret(node.server_key_pem_encrypted),
        "tls-crypt.key": decrypt_secret(ca.tls_crypt_key_encrypted),
        "crl.pem": crl_pem,
    }
    if node.tcp_port:
        files["server-tcp.conf"] = render_server_config(
            node, proto="tcp", port=node.tcp_port
        )
    # Written last on purpose: the OpenVPN supervisor waits for this file and
    # starts as soon as it appears, so everything else must already be there.
    files["server.conf"] = render_server_config(node)

    # A rewritten server.conf changes nothing until OpenVPN reloads it: the
    # running process holds the old options in memory. The agent flags its own
    # rewrites; this covers the panel writing the bundle at startup, which is how
    # a new template reaches the local node.
    changed = any(
        not (target / name).exists() or (target / name).read_text() != content
        for name, content in files.items()
        if name.endswith(".conf")
    )

    for name, content in files.items():
        path = target / name
        path.write_text(content)
        # Private material must not be world-readable inside the shared volume.
        path.chmod(0o600 if name in {"server.key", "tls-crypt.key"} else 0o644)

    if changed:
        (target / ".restart").write_text(str(time.time()))
        logger.warning("Server config changed, asked the supervisor to restart OpenVPN")

    logger.warning("Wrote OpenVPN bundle for node %r to %s", node.name, target)
    return target
