"""Rendering of OpenVPN server and client configuration.

The panel owns the whole configuration: nodes and clients never hold state the
panel cannot rebuild from the database.
"""

import logging
from pathlib import Path

from app.core.config import settings
from app.core.crypto import decrypt_secret
from app.models.node import Client, Node
from app.models.pki import CertificateAuthority
from app.services import pki

logger = logging.getLogger("aeolus.openvpn")


class OpenVpnError(Exception):
    """Configuration could not be produced. Safe to show to an operator."""


def render_server_config(node: Node, *, proto: str | None = None, port: int | None = None) -> str:
    """Server config for one listener of a node. Certificates live in siblings."""
    proto = proto or node.openvpn_proto
    port = port or node.openvpn_port
    # TCP needs its own status file and management port, or the two instances
    # would overwrite each other.
    suffix = "" if proto == "udp" else "-tcp"
    return f"""# Generated by Aeolus. Changes are overwritten on restart.
port {port}
proto {"tcp-server" if proto == "tcp" else "udp"}
dev tun
topology subnet

server {settings.vpn_subnet if proto == "udp" else settings.vpn_tcp_subnet} {settings.vpn_netmask}
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS {settings.vpn_dns}"

ca ca.crt
cert server.crt
key server.key
# EC certificates use ECDH, so no Diffie-Hellman parameter file is needed.
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
# OpenVPN re-reads the CRL on every handshake, so rewriting this file is enough
# to start refusing a revoked client.
crl-verify crl.pem
client-config-dir ccd

data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client

# A 1500-byte tunnel MTU makes the encapsulated packet exceed the path MTU on
# most mobile networks, which drop it. Small packets then work while anything
# large — TLS, QUIC — silently stalls. Leave headroom for the UDP, tls-crypt and
# AES-GCM overhead, and clamp TCP MSS to match.
tun-mtu {settings.vpn_tun_mtu}
mssfix {settings.vpn_mssfix}

keepalive 10 120
persist-key
persist-tun
user nobody
group nogroup

status /run/openvpn/status{suffix}.log 5
management 127.0.0.1 {7505 if proto == "udp" else 7506}
verb 3
"""


def render_client_config(client: Client, node: Node, ca: CertificateAuthority) -> str:
    """A single self-contained .ovpn file with everything inlined."""
    if client.cert_pem is None or client.key_pem_encrypted is None:
        raise OpenVpnError(
            f"{client.common_name} has no certificate yet; issue one in the pki section"
        )
    if client.revoked_at is not None:
        raise OpenVpnError(f"{client.common_name} is revoked")

    key_pem = decrypt_secret(client.key_pem_encrypted)
    tls_crypt = decrypt_secret(ca.tls_crypt_key_encrypted)

    # Plain repeated remote lines, not <connection> blocks: options that follow a
    # connection block are silently ignored by OpenVPN 2.x, which would drop
    # tls-crypt and leave the profile unusable. The client tries these in order,
    # so UDP comes first — it is faster, and TCP-in-TCP degrades badly on loss.
    remotes = f"remote {node.address} {node.openvpn_port} {node.openvpn_proto}"
    if node.tcp_port:
        remotes += f"\nremote {node.address} {node.tcp_port} tcp"

    return f"""# Aeolus · {client.common_name} via {node.name}
client
dev tun
{remotes}
# Move on to the next remote instead of retrying a transport the network mangles.
connect-retry-max 2
server-poll-timeout 12
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
verb 3

<ca>
{ca.cert_pem.strip()}
</ca>
<cert>
{client.cert_pem.strip()}
</cert>
<key>
{key_pem.strip()}
</key>
<tls-crypt>
{tls_crypt.strip()}
</tls-crypt>
"""


async def sync_local_crl(session) -> bool:
    """Refresh the CRL the local OpenVPN reads.

    Revocation is only real once the node has the new list, so this runs on
    every revoke rather than waiting for the next restart. Remote nodes will get
    the same file from the anemoi agent.
    """
    target = Path(settings.openvpn_config_dir)
    if not target.exists():
        return False

    crl_pem = await pki.build_crl(session)
    (target / "crl.pem").write_text(crl_pem)
    logger.warning("Refreshed CRL at %s", target / "crl.pem")
    return True


def write_server_bundle(node: Node, ca: CertificateAuthority, crl_pem: str) -> Path:
    """Write everything the local OpenVPN process needs into the shared volume.

    Used for the panel's own node; remote nodes will get the same bundle pushed
    by the anemoi agent instead.
    """
    if node.server_cert_pem is None or node.server_key_pem_encrypted is None:
        raise OpenVpnError(f"node {node.name} has no server certificate")

    target = Path(settings.openvpn_config_dir)
    target.mkdir(parents=True, exist_ok=True)
    (target / "ccd").mkdir(exist_ok=True)

    files = {
        "ca.crt": ca.cert_pem,
        "server.crt": node.server_cert_pem,
        "server.key": decrypt_secret(node.server_key_pem_encrypted),
        "tls-crypt.key": decrypt_secret(ca.tls_crypt_key_encrypted),
        "crl.pem": crl_pem,
    }
    if node.tcp_port:
        files["server-tcp.conf"] = render_server_config(
            node, proto="tcp", port=node.tcp_port
        )
    # Written last on purpose: the OpenVPN supervisor waits for this file and
    # starts as soon as it appears, so everything else must already be there.
    files["server.conf"] = render_server_config(node)

    for name, content in files.items():
        path = target / name
        path.write_text(content)
        # Private material must not be world-readable inside the shared volume.
        path.chmod(0o600 if name in {"server.key", "tls-crypt.key"} else 0o644)

    logger.warning("Wrote OpenVPN bundle for node %r to %s", node.name, target)
    return target
