"""Rendering of OpenVPN server and client configuration.

The panel owns the whole configuration: nodes and clients never hold state the
panel cannot rebuild from the database.
"""

import logging
from pathlib import Path

from app.core.config import settings
from app.core.crypto import decrypt_secret
from app.models.node import Client, Node
from app.models.pki import CertificateAuthority
from app.services import pki

logger = logging.getLogger("aeolus.openvpn")


class OpenVpnError(Exception):
    """Configuration could not be produced. Safe to show to an operator."""


def render_server_config(node: Node) -> str:
    """Server config for a node. Certificates live in sibling files."""
    return f"""# Generated by Aeolus. Changes are overwritten on restart.
port {node.openvpn_port}
proto {node.openvpn_proto}
dev tun
topology subnet

server {settings.vpn_subnet} {settings.vpn_netmask}
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS {settings.vpn_dns}"

ca ca.crt
cert server.crt
key server.key
# EC certificates use ECDH, so no Diffie-Hellman parameter file is needed.
dh none
ecdh-curve prime256v1
tls-crypt tls-crypt.key
# OpenVPN re-reads the CRL on every handshake, so rewriting this file is enough
# to start refusing a revoked client.
crl-verify crl.pem
client-config-dir ccd

data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
remote-cert-tls client

keepalive 10 120
persist-key
persist-tun
user nobody
group nogroup

status /run/openvpn/status.log 5
management 127.0.0.1 7505
verb 3
"""


def render_client_config(client: Client, node: Node, ca: CertificateAuthority) -> str:
    """A single self-contained .ovpn file with everything inlined."""
    if client.cert_pem is None or client.key_pem_encrypted is None:
        raise OpenVpnError(
            f"{client.common_name} has no certificate yet; issue one in the pki section"
        )
    if client.revoked_at is not None:
        raise OpenVpnError(f"{client.common_name} is revoked")

    key_pem = decrypt_secret(client.key_pem_encrypted)
    tls_crypt = decrypt_secret(ca.tls_crypt_key_encrypted)

    return f"""# Aeolus · {client.common_name} via {node.name}
client
dev tun
proto {node.openvpn_proto}
remote {node.address} {node.openvpn_port}
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-GCM
auth SHA256
tls-version-min 1.2
verb 3

<ca>
{ca.cert_pem.strip()}
</ca>
<cert>
{client.cert_pem.strip()}
</cert>
<key>
{key_pem.strip()}
</key>
<tls-crypt>
{tls_crypt.strip()}
</tls-crypt>
"""


async def sync_local_crl(session) -> bool:
    """Refresh the CRL the local OpenVPN reads.

    Revocation is only real once the node has the new list, so this runs on
    every revoke rather than waiting for the next restart. Remote nodes will get
    the same file from the anemoi agent.
    """
    target = Path(settings.openvpn_config_dir)
    if not target.exists():
        return False

    crl_pem = await pki.build_crl(session)
    (target / "crl.pem").write_text(crl_pem)
    logger.warning("Refreshed CRL at %s", target / "crl.pem")
    return True


def write_server_bundle(node: Node, ca: CertificateAuthority, crl_pem: str) -> Path:
    """Write everything the local OpenVPN process needs into the shared volume.

    Used for the panel's own node; remote nodes will get the same bundle pushed
    by the anemoi agent instead.
    """
    if node.server_cert_pem is None or node.server_key_pem_encrypted is None:
        raise OpenVpnError(f"node {node.name} has no server certificate")

    target = Path(settings.openvpn_config_dir)
    target.mkdir(parents=True, exist_ok=True)
    (target / "ccd").mkdir(exist_ok=True)

    files = {
        "ca.crt": ca.cert_pem,
        "server.crt": node.server_cert_pem,
        "server.key": decrypt_secret(node.server_key_pem_encrypted),
        "tls-crypt.key": decrypt_secret(ca.tls_crypt_key_encrypted),
        "crl.pem": crl_pem,
        "server.conf": render_server_config(node),
    }

    for name, content in files.items():
        path = target / name
        path.write_text(content)
        # Private material must not be world-readable inside the shared volume.
        path.chmod(0o600 if name in {"server.key", "tls-crypt.key"} else 0o644)

    logger.warning("Wrote OpenVPN bundle for node %r to %s", node.name, target)
    return target
