"""agent enrolment and grpc identity

Revision ID: 512c11908ae8
Revises: f2e382457c70
Create Date: 2026-08-19 17:21:47.180299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512c11908ae8'
down_revision: Union[str, Sequence[str], None] = 'f2e382457c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authority', sa.Column('grpc_cert_pem', sa.Text(), nullable=True))
    op.add_column('certificate_authority', sa.Column('grpc_key_pem_encrypted', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('enrollment_token_hash', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('enrollment_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('nodes', sa.Column('agent_cert_serial', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('agent_cert_not_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('nodes', sa.Column('agent_version', sa.String(length=32), nullable=True))
    op.add_column('nodes', sa.Column('config_revision', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('nodes_agent_cert_fingerprint_key'), 'nodes', type_='unique')
    op.create_index(op.f('ix_nodes_enrollment_token_hash'), 'nodes', ['enrollment_token_hash'], unique=False)
    op.drop_column('nodes', 'agent_cert_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('agent_cert_fingerprint', sa.VARCHAR(length=95), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_nodes_enrollment_token_hash'), table_name='nodes')
    op.create_unique_constraint(op.f('nodes_agent_cert_fingerprint_key'), 'nodes', ['agent_cert_fingerprint'], postgresql_nulls_not_distinct=False)
    op.drop_column('nodes', 'config_revision')
    op.drop_column('nodes', 'agent_version')
    op.drop_column('nodes', 'agent_cert_not_after')
    op.drop_column('nodes', 'agent_cert_serial')
    op.drop_column('nodes', 'enrollment_token_expires_at')
    op.drop_column('nodes', 'enrollment_token_hash')
    op.drop_column('certificate_authority', 'grpc_key_pem_encrypted')
    op.drop_column('certificate_authority', 'grpc_cert_pem')
    # ### end Alembic commands ###
