"""tcp listener port per node

Revision ID: 641116e53cf5
Revises: 512c11908ae8
Create Date: 2026-08-19 17:48:38.057530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641116e53cf5'
down_revision: Union[str, Sequence[str], None] = '512c11908ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('tcp_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'tcp_port')
    # ### end Alembic commands ###
