"""node metrics, roles, client last-seen

Revision ID: df914fea138d
Revises: b5d7a192ce4d
Create Date: 2026-08-19 15:13:29.346314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df914fea138d'
down_revision: Union[str, Sequence[str], None] = 'b5d7a192ce4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('clients', sa.Column('last_node_id', sa.Uuid(), nullable=True))
    op.alter_column('clients', 'traffic_limit_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('clients', 'traffic_used_bytes',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_foreign_key(
        'fk_clients_last_node_id', 'clients', 'nodes', ['last_node_id'], ['id'],
        ondelete='SET NULL',
    )
    # add_column does not create the enum type itself, so do it explicitly.
    node_role = sa.Enum('master', 'slave', name='node_role')
    node_role.create(op.get_bind(), checkfirst=True)

    # server_default keeps these adds valid on a table that already has rows.
    op.add_column('nodes', sa.Column('role', node_role, nullable=False, server_default='slave'))
    op.add_column('nodes', sa.Column('sessions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('bandwidth_mbps', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('bandwidth_capacity_mbps', sa.Integer(), nullable=False, server_default='1000'))
    op.add_column('nodes', sa.Column('rx_bytes', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('tx_bytes', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('nodes', sa.Column('server_cert_not_after', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'server_cert_not_after')
    op.drop_column('nodes', 'tx_bytes')
    op.drop_column('nodes', 'rx_bytes')
    op.drop_column('nodes', 'bandwidth_capacity_mbps')
    op.drop_column('nodes', 'bandwidth_mbps')
    op.drop_column('nodes', 'sessions')
    op.drop_column('nodes', 'role')
    sa.Enum(name='node_role').drop(op.get_bind(), checkfirst=False)
    op.drop_constraint('fk_clients_last_node_id', 'clients', type_='foreignkey')
    op.alter_column('clients', 'traffic_used_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('clients', 'traffic_limit_bytes',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('clients', 'last_node_id')
    op.drop_column('clients', 'last_seen_at')
    # ### end Alembic commands ###
