"""certificate authority and stored key material

Revision ID: f2e382457c70
Revises: df914fea138d
Create Date: 2026-08-19 15:46:18.115344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e382457c70'
down_revision: Union[str, Sequence[str], None] = 'df914fea138d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_authority',
    sa.Column('common_name', sa.String(length=64), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('key_pem_encrypted', sa.Text(), nullable=False),
    sa.Column('tls_crypt_key_encrypted', sa.Text(), nullable=False),
    sa.Column('next_serial', sa.BigInteger(), nullable=False),
    sa.Column('crl_number', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('key_pem_encrypted', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('server_cert_pem', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('server_key_pem_encrypted', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('server_cert_serial', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'server_cert_serial')
    op.drop_column('nodes', 'server_key_pem_encrypted')
    op.drop_column('nodes', 'server_cert_pem')
    op.drop_column('clients', 'key_pem_encrypted')
    op.drop_table('certificate_authority')
    # ### end Alembic commands ###
